version: "3.9"

networks:
  my_network:
volumes:
  pgdata:

services:
  postgredb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "new_db"
      POSTGRES_USER: "admin1"
      POSTGRES_PASSWORD: "admin1"
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin1 admin1 -a new_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log
    networks:
      - my_network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "aaa@aaa.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - my_network
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    networks:
      - my_network      
  redis:
    image: "redis:alpine"
    networks:
      - my_network